# Arithmetic Operation

In [1]:
import numpy as np

In [2]:
d = np.arange(12).reshape(3,4)

In [3]:
e = np.arange(12).reshape(4,3)

In [4]:
d + e

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [5]:
e = np.arange(12).reshape(3,4)

In [6]:
e + d

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
l1 = [1,2,3]
l2 = [4,5,6]
l1 + l2 # concatenate

[1, 2, 3, 4, 5, 6]

In [9]:
d-e

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
d * e

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# Matrix Multiplication

In [23]:
a = np.arange(1,13).reshape(4,3)

In [27]:
b = np.arange(1,13).reshape(3,4)

In [28]:
a, b

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [29]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

In [22]:
np.matmul(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200],
       [173, 206, 239, 272]])

# Shallow Copy and Deep Copy

In [45]:
import numpy as np

a = np.array([1,2,3])
b = a        # shallow copy
c = a.view() # shallow copy
d = a.copy() # deep copy
e = a[0:3]   # shallow copy

print(id(a), id(b))  # same object
print(id(c))         # different object
print(id(d))         # different object
print(id(e))         # different object

134720892234576 134720892234576
134720892234864
134720892234960
134720892235056


In [46]:
d[2] = 30
d[1] = 10
e[0] = 99
a,b,c,d,e

(array([99,  2,  3]),
 array([99,  2,  3]),
 array([99,  2,  3]),
 array([ 1, 10, 30]),
 array([99,  2,  3]))

In [47]:
np.shares_memory(a,b)

True

In [49]:
np.shares_memory(a,e)

True

In [50]:
h = a[a%1 == 0]

In [51]:
np.shares_memory(a,h)

False

# Splitting

In [52]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [55]:
np.split(a, (4,6))

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [57]:
mat = np.arange(16).reshape(4,4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
np.split(mat, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [59]:
np.split(mat, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Stacking

In [93]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.vstack((a, b))
result

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [96]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [88]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [89]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [92]:
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])