# Dimension, Shapes & Arange

In [ ]:
import numpy as np

In [ ]:
arr = np.array(range(10))

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.shape

(10,)

In [ ]:
arr2 = np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8]])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr3 = np.array([[1,2,3,4]])

In [ ]:
arr3

array([[1, 2, 3, 4]])

In [ ]:
arr3.shape

(1, 4)

In [ ]:
arr.ndim

1

In [ ]:
arr3.ndim

2

In [ ]:
np.arange(3.5)

array([0., 1., 2., 3.])

In [ ]:
np.arange(0,3.5,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25])

#Type conversion

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
np.array([1,2,3,4.]) #upcasted

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4.2], dtype= int)

array([1, 2, 3, 4])

In [ ]:
np.array(['1','2'], dtype=int)

array([1, 2])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.astype(float)

array([1., 2., 3., 4.])

# Slicing

In [ ]:
a = np.array([8,7,6])

In [ ]:
a[::-2]

array([6, 8])

In [ ]:
a[::1]

array([8, 7, 6])

In [ ]:
a[::-1]

array([6, 7, 8])

In [ ]:
a[1:-3:-1]

array([7])

In [ ]:
a[::2]

array([8, 6])